<?php

const SYSTEM_CONFIGURATIONS_SITE_OFF_LINE = 'SITE_OFF_LINE';
const SYSTEM_CONFIGURATIONS_OTP_EXPIRE_DURATION = 'OTP_EXPIRE_DURATION';
const SYSTEM_CONFIGURATIONS_LOGIN_MOBILE_VERIFICATION = 'LOGIN_MOBILE_VERIFICATION';
const SYSTEM_CONFIGURATIONS_LOGIN_SESSION_EXPIRE_HOURS = 'LOGIN_SESSION_EXPIRE_HOURS';
const SYSTEM_CONFIGURATIONS_MOBILE_SMS_API_TOKEN = 'MOBILE_SMS_API_TOKEN';
const SYSTEM_CONFIGURATIONS_UPLOADED_IMAGE_BASEURL = 'UPLOADED_IMAGE_BASEURL';
const SYSTEM_CONFIGURATIONS_FISCAL_YEAR_STARTING_MONTH = 'FISCAL_YEAR_STARTING_MONTH';


